repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.18.2
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
