name: tag release changelog

on:
  workflow_call:
    inputs:
      use_v_prefix:
        description: "Prefix tags with 'v'"
        required: false
        default: true
        type: boolean
    outputs:
      tag:
        description: Release tag
        value: ${{ jobs.tag-releases.outputs.tag }}

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        id: bump_tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: ${{ inputs.use_v_prefix }}
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump_tag.outputs.tag }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag: ${{ steps.bump_tag.outputs.tag }}
