name: terraform plan apply

on:
  workflow_call:
    inputs:
      configuration-dir:
        description: "Name of the terraform configuration directory in repository root"
        required: true
        default: "configuration"
        type: string
      terraform-dir:
        description: "Name of the terraform directory in repository root"
        required: true
        default: "terraform"
        type: string
      aws-region:
        description: "AWS Default Region"
        required: false
        default: "eu-west-1"
        type: string
      backend-tfvars-suffix:
        description: "Backend tfvar file suffix"
        required: false
        default: "backend.tfvars"
        type: string
      tfvars-suffix:
        description: "Tfvar file suffix"
        required: false
        default: "tfvars"
        type: string
      tfm-plan-file:
        description: "File to output plan"
        required: false
        default: "tfm.plan"
        type: string
      debug:
        description: "Enable to get additional output"
        required: false
        default: false
        type: boolean
      enable-snyk-scan:
        description: "Enable Snyk scan"
        required: false
        default: false
        type: boolean
      download-artifacts:
        description: "Download artifacts"
        required: false
        default: false
        type: boolean
      artifacts-dir:
        description: "Artifacts folder"
        required: false
        default: artifacts
        type: string

    secrets:
      aws-access-key-id:
        description: "AWS Access Key Id - cicd-automation user"
        required: true
      aws-secret-access-key:
        description: "AWS Secret Access Key - cicd-automation user"
        required: true
      aws-cicd-automation-role-external-id:
        description: "External ID used when assuming CICD automation role"
        required: true
      aws-cicd-automation-github-role:
        description: "CICD Automation Role for Github actions"
        required: true
      snyk-token:
        description: "SNYK token"
        required: false

jobs:
  ## GET CHANGED FILES
  ## Get list of files that have changed
  get-changes:
    name: get-changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: shell
          filters: |
            cfg:
              - "${{ inputs.configuration-dir }}/**"
            tfm:
              - "${{ inputs.terraform-dir }}/**/*.tf"
      - name: Get changed files
        id: get-changed-files
        run: |
          changed_cfg_files="${{ steps.changes.outputs.cfg_files }}"
          changed_tfm_files="${{ steps.changes.outputs.tfm_files }}"

          tfm_changed="${{ steps.changes.outputs.tfm }}"
          cfg_changed="${{ steps.changes.outputs.cfg }}"

          matrix="{\"prefix\":[]}"

          if [ "$tfm_changed" == "true" ]; then
              files=$(find ${{ inputs.configuration-dir }} -type f | tr "\n" " ")
              tfm_files="[\"$(echo $changed_tfm_files  | sed -e 's/ /\", \"/g' )\"]"
          else 
            files="$(echo $changed_cfg_files)"
          fi

          for file in $files; do
              if [[ "$file" != *.${{ inputs.backend-tfvars-suffix }} ]]; then
                  prefix="${file/.${{ inputs.tfvars-suffix }}/}"                  
                  matrix=$( echo $matrix | jq -c --arg prefix "$prefix" '.prefix += [$prefix]')
              fi
          done

          tfm_matrix=$tfm_files

          if [ "$tfm_changed" == "false" ] && [ "$cfg_changed" == "false" ]; then matrix="none"; fi
          if [ "$tfm_changed" == "false" ] ; then tfm_matrix="none"; fi

          echo "matrix: $matrix"
          echo "tfm_matrix: $tfm_matrix"

          echo "::set-output name=matrix::$matrix"
          echo "::set-output name=tfm_matrix::$tfm_matrix"
    outputs:
      matrix: ${{ steps.get-changed-files.outputs.matrix }}
      tfm_matrix: ${{ steps.get-changed-files.outputs.tfm_matrix }}

  plan-deployment:
    runs-on: ubuntu-latest
    needs: [get-changes]
    if: ${{ needs.get-changed-files.outputs.matrix }} != 'none'
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-changes.outputs.matrix) }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: create-artifacts-dir
        run: |
          mkdir -p ${{ inputs.artifacts-dir }}
      - name: download-artifacts
        if: ${{ inputs.download-artifacts }} == true
        uses: actions/download-artifact@v3
        with:
          path: ${{ inputs.artifacts-dir }}
      - name: Display structure of downloaded files
        if: ${{ inputs.download-artifacts }} == true
        run: ls -R
        working-directory: ${{ inputs.artifacts-dir }}

      - name: cleanup .terraform folder
        run: rm -f .terraform

      - name: update version in tfvars
        run: |
          prefix=${{ matrix.prefix }}
          suffix=${{ inputs.tfvars-suffix }}

          LATEST_TAG=$(/usr/bin/git describe --abbrev=0 --tags)
          if [ -z "$LATEST_TAG" ]; then 
            SERVICE_VERSION="v0.0.0"
          else
            SERVICE_VERSION="$LATEST_TAG"
          fi
          TFVARS="$prefix.$suffix"
          sed -i "s#<service-version>#$SERVICE_VERSION#g" $TFVARS

      - name: Configure AWS Credentials for cicd-automation
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws-region }}
          mask-aws-account-id: "yes"
          role-to-assume: ${{ secrets.aws-cicd-automation-github-role }}
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: terraform apply
        run: |
          prefix=${{ matrix.prefix }}
          suffix=${{ inputs.tfvars-suffix }}

          echo "Running terraform init for $product product"
          terraform init --backend-config="../${prefix}.backend.${suffix}" 

          echo "Running terraform plan for $product"
          terraform plan --var-file="../${prefix}.${suffix}" \
            -var "aws_role_external_id=${{ secrets.aws-cicd-automation-role-external-id }}" \
            -out=${{ inputs.tfm-plan-file }}

          echo "Apply terraform plan"
          terraform apply -auto-approve ${{ inputs.tfm-plan-file }}
        working-directory: ${{ inputs.terraform-dir }}
